#+title: Aulas FCUL
#+date: [2026-03-06 Fri 18:38]

* Aulas FCUL :lectures:

  Lecture notes e outros apontamentos sobre as aulas de Functional Programming
  in Haskell na FCUL que estou a dar como Prof. Auxiliar Convidado.

  Objectivo cadeira:

    Adquirir conceitos básicos da programação com especial foco na programação
    funcional e experiência prática na escrita de programas funcionais usando a
    linguagem Haskell.

* Semana 1

** Turno 2

   Motivação para aprender Haskell:
    Tornar-se mais simples, claro, e elegante pensar, programar, resolver
   problemas e escrever algoritmos entre várias outras coisas como tornar mais
   claro várias ideias de computer science.

   Um PROGRAMA de Haskell é apenas um conjunto de DECLARAÇÕES
   Uma declaração é um nome/função e uma EXPRESSÃO

   Em Haskell, programar é apenas escrever expressões compostas de subexpressões.
   O programa final é uma expressão gigante.

The most important thing to take away:
   _Todas as expressões têm tipos._

   Quando tiverem alguma dúvida em relação ao programa que
   estiverem a escrever, identifiquem todas as sub-expressões e
   dêm um TIPO a cada uma. Facilmente vão perceber onde pode estar
   algo errado.

   O exemplo do programa errado que trabalhamos:

   #+begin_src haskell
   -- Concatena 2 numeros (-123 e 4 ==> -1234)
   f :: Int -> Int -> Int
   f x y = read (x ++ y)
   #+end_src

   Aplicar ideia de dar um tipo a cada nome e a cada (sub)expressão.

   Variáveis e aplicação de funções.

* Semana 2

** Ideias

   - Repetir no turno 1 a ideia importante de todas as expressões
     terem tipos. Repetir também Motivação (ver acima)

   - Identificar as Core features do Haskell que eles aprenderam
     até agora, especialmente pq vai ser interessante depois
     introduzir Cases como uma coisa "fundamental" acho eu.

** Turno 1

   Voltar a analizar expressões e tipos;
   Case expressions; wheres vs lets;
   Mostrar os 6 tipos de expressões que o Haskell usa under the hood, a forma mais simples:

    Literals + Var + FunApp + LamAbs + Cases + Lets

   Expressões no fim são só isso. As outras formas sintáticas ajudam a escrever
   programas mais elegantes e diretos, mas se quisessemos ter tudo por extenso
   bastavam estas 6 coisas para representar todas as expressões em Haskell (sem
   contar com cast/coercions, type, and ticks)

   Exercício espontâneo para um aluno (Miguel) que está a repetir a cadeira e
   tem facilidade com matemática mas não com programação. Ele está mais
   avançado mas este foi ótimo para o seu nível e interessante:

   #+begin_src haskell
    data Nat = Zero
             | Succ Nat
    -- Exercise is to define in this order

    toInt :: Nat -> Int
    instance Show Nat where show = _
    inc :: Nat -> Nat
    add :: Nat -> Nat
    mul :: Nat -> Nat
   #+end_src

** Turno 2

    Wheres vs Lets
    Function types
    Math sets vs list comprehensions
    A few more things

* Semana 3

** Turno 1

   how lets are evaluated
