#+title: Aulas FCUL
#+date: [2026-03-06 Fri 18:38]

* Aulas FCUL :lectures:

  Lecture notes e outros apontamentos sobre as aulas de Functional Programming
  in Haskell na FCUL que estou a dar como Prof. Auxiliar Convidado.

  Objectivo cadeira:

    Adquirir conceitos básicos da programação com especial foco na programação
    funcional e experiência prática na escrita de programas funcionais usando a
    linguagem Haskell.

* Semana 1

** Turno 2

   Motivação para aprender Haskell:
    Tornar-se mais simples, claro, e elegante pensar, programar, resolver
   problemas e escrever algoritmos entre várias outras coisas como tornar mais
   claro várias ideias de computer science.

   Um PROGRAMA de Haskell é apenas um conjunto de DECLARAÇÕES
   Uma declaração é um nome/função e uma EXPRESSÃO

   Em Haskell, programar é apenas escrever expressões compostas de subexpressões.
   O programa final é uma expressão gigante.

The most important thing to take away:
   _Todas as expressões têm tipos._

   Quando tiverem alguma dúvida em relação ao programa que
   estiverem a escrever, identifiquem todas as sub-expressões e
   dêm um TIPO a cada uma. Facilmente vão perceber onde pode estar
   algo errado.

   O exemplo do programa errado que trabalhamos:

   #+begin_src haskell
   -- Concatena 2 numeros (-123 e 4 ==> -1234)
   f :: Int -> Int -> Int
   f x y = read (x ++ y)
   #+end_src

   Aplicar ideia de dar um tipo a cada nome e a cada (sub)expressão.

   Variáveis e aplicação de funções.

* Semana 2

** Ideias

   - Repetir no turno 1 a ideia importante de todas as expressões
     terem tipos. Repetir também Motivação (ver acima)

   - Identificar as Core features do Haskell que eles aprenderam
     até agora, especialmente pq vai ser interessante depois
     introduzir Cases como uma coisa "fundamental" acho eu.
