#+bibliography: ../references.bib
#+title: Tony's Thesis
#+date: [2026-03-04 Wed 23:45]

* Propagation of reachable sets

  Reachable sets: space that a drone/system can reach in a single step

  If the drone system was a linear system, it'd be easy to propagate the
  reachable set using zonotopes.

  With non-linear systems, it's much harder to propagate reachable sets (to next steps).
  The work [cite:@harapanahalli2025parametricreachablesetscontrolled] attempts to
  do reachable set propagation for non-linear systems using so-called parametopes.

  What is a reachable set?
  A reachable set is represented by an inequality between two functions

    g(x) <= h(x)

  The left hand side is called the generator function (g), the right hand side
  can be considered the radius

  Parametopes propagates the generator function as a set of vectors

* Further reading

  [[https://coogan.ece.gatech.edu/papers/pdf/harapanahalli2024immrax.pdf][Computing interval analysis and mixed monotone reachability]]

  Mixed monotone reachability:
    [[https://coogan.ece.gatech.edu/papers/pdf/jafarpour2023interactiontac.pdf][Efficient Interaction-Aware Interval Analysis of Neural Network Feedback Loops]]

  Interval analysis on dynamic systems using differential equations:
    [[https://www.sciencedirect.com/science/article/abs/pii/S0098135417302934][Rapid and accurate reachability analysis for nonlinear dynamic systems by exploiting model redundancy]]
    - A method is presented for accurately bounding the reachable sets of ODEs.

    
