#+title: Aulas FCUL
#+date: [2026-03-06 Fri 18:38]

* Aulas FCUL :lectures:

  Lecture notes e outros apontamentos sobre as aulas de Functional Programming
  in Haskell na FCUL que estou a dar como Prof. Auxiliar Convidado.

  Objectivo cadeira:

    Adquirir conceitos básicos da programação com especial foco na programação
    funcional e experiência prática na escrita de programas funcionais usando a
    linguagem Haskell.

* Semana 1

** Turno 2

   Motivação para aprender Haskell:
    Tornar-se mais simples, claro, e elegante pensar, programar, resolver
   problemas e escrever algoritmos entre várias outras coisas como tornar mais
   claro várias ideias de computer science.

   Um PROGRAMA de Haskell é apenas um conjunto de DECLARAÇÕES
   Uma declaração é um nome/função e uma EXPRESSÃO

   Em Haskell, programar é apenas escrever expressões compostas de subexpressões.
   O programa final é uma expressão gigante.

The most important thing to take away:
   _Todas as expressões têm tipos._

   Quando tiverem alguma dúvida em relação ao programa que
   estiverem a escrever, identifiquem todas as sub-expressões e
   dêm um TIPO a cada uma. Facilmente vão perceber onde pode estar
   algo errado.

   O exemplo do programa errado que trabalhamos:

   #+begin_src haskell
   -- Concatena 2 numeros (-123 e 4 ==> -1234)
   f :: Int -> Int -> Int
   f x y = read (x ++ y)
   #+end_src

   Aplicar ideia de dar um tipo a cada nome e a cada (sub)expressão.

   Variáveis e aplicação de funções.

* Semana 2

** Ideias

   - Repetir no turno 1 a ideia importante de todas as expressões
     terem tipos. Repetir também Motivação (ver acima)

   - Identificar as Core features do Haskell que eles aprenderam
     até agora, especialmente pq vai ser interessante depois
     introduzir Cases como uma coisa "fundamental" acho eu.

** Turno 1

   Voltar a analizar expressões e tipos;
   Case expressions; wheres vs lets;
   Mostrar os 6 tipos de expressões que o Haskell usa under the hood, a forma mais simples:

    Literals + Var + FunApp + LamAbs + Cases + Lets

   Expressões no fim são só isso. As outras formas sintáticas ajudam a escrever
   programas mais elegantes e diretos, mas se quisessemos ter tudo por extenso
   bastavam estas 6 coisas para representar todas as expressões em Haskell (sem
   contar com cast/coercions, type, and ticks)

   Exercício espontâneo para um aluno (Miguel) que está a repetir a cadeira e
   tem facilidade com matemática mas não com programação. Ele está mais
   avançado mas este foi ótimo para o seu nível e interessante:

   #+begin_src haskell
    data Nat = Zero
             | Succ Nat
    -- Exercise is to define in this order

    toInt :: Nat -> Int
    instance Show Nat where show = _
    inc :: Nat -> Nat
    add :: Nat -> Nat
    mul :: Nat -> Nat
   #+end_src

** Turno 2

    Wheres vs Lets
    Function types
    Math set notation vs list comprehensions (not that different!)
    Functions as first-class values (f :: a -> b, f = g well defined for some g :: a -> b)
    A few more things

** Observações

   Alunos tiveram bastantes dúvidas sobre a diferença entre os lets e os wheres.
   Para além disso, achavam que eram precisos usar de alguma forma, qnd na
   verdade é só uma forma de introduzir local bindings.

   Parece-me desnecessário introduzir `where`s de todo. No fim do dia são
   desugared para `where`s e tudo. IMO só confunde introduzir esta forma
   sintática a mais. Mais opções não é necessáriamente bom, especialmente nesta
   fase. Gastámos muito tempo a esclarecer as diferenças na aula (que no fim
   são só a syntax e as lexical scopes serem ligeiramente diferentes)

   Seria interessante se a aula usasse apenas as 6 formas Core do Haskell
    - Literal
    - Var
    - Lambda
    - App
    - Let
    - Case

   As outras (Type, Cast, Coercion, Tick) não são necessárias para o primeiro ano (e na verdade não se escrevem facilmente em Source Haskell).
   Claro que há muito a dizer para além destas 6 formas primitivas de construir
   /expressões/, e.g. sobre types, datatypes, typeclass, e um milhão de outras
   coisas que source Haskell tem que permitem exprimir ideias importantes sem
   ter de estar a usar coercions manualmente.

* Semana 3

** Ideias

   - ~~Maquina de Turing e o Lambda Calculus?~~
   - ~~Programa simples gráfico com Brillo/Gloss?~~

     Nope.

** Turno 1

   How lets are evaluated

** Turno 2

   Recursion via proofs by induction (bad) assembly loops (good) (label+jump; why does a
   loop with a jump terminate? because there's an exit condition; same for
   Haskell recursion) and referential transparency algebraic reasoning style
   (good) (ie reduce sum [1,2,3] with equations)

* Semana 4

** Turno 1

   Trabalhar lambdas, currying, higher order functions, eta reducion
   Exercício: what's the type of (.) f g x = f (g x)
   Tail call recursion

** Turno substituição

   Lambdas, partial application, currying
   Desafios: Type of (.); Implement `curry`, implement `uncurry`.
   Bom feedback da aula

** Turno 2


